cmd: support OLLAMA_CLIENT_HOST environment variable
jmorganca/ollama pull request #262
Opened 2023-08-02 22:05 UTC by bmizerany

This commit adds support for the OLLAMA_CLIENT_HOST environment variable. This variable can be used to specify the host to which the client should connect. This is useful when the client is running somewhere other than the host where the server is running.

The new api.FromEnv function is used to read configure clients from the environment. Clients wishing to use the environment variable being consistent with the Ollama CLI can use this new function.

2023-08-03 17:55 UTC, drhino commented
This is already implemented in:
https://github.com/jmorganca/ollama/blob/main/cmd/cmd.go#L517

2023-08-03 20:18 UTC, drhino commented
Only noticed #261 now
Maybe you want to update this file too:
https://github.com/jmorganca/ollama/blob/main/server/routes.go#L308

2023-08-04 05:38 UTC, bmizerany commented
That is a change required for any client to work, or just browsers?

If only the latter, maybe that is for another PR?

2023-08-04 05:39 UTC, drhino commented
I think thats only for the browser.. But it would be great to have!

2023-08-04 05:49 UTC, bmizerany commented
Agreed. Maybe that's for another PR? I'm not seeing docs mention browser support atm, which leads me to think this isn't the right PR for browser support.

2023-08-04 13:43 UTC, justinmayer requested changes
I made a few minor suggestions. In addition, I don't think this should be merged until accompanying documentation is added, preferably to the README since the `docs` directory isn't linked anywhere and is thus very hard to discover at the moment.

2023-08-04 13:43 UTC, justinmayer commented on api/client.go
> +func Host() string {
I think `Host()` is a bit too generic. What if other host-related functions are added later? I think `GetHost()` would be more specific and descriptive.

2023-08-04 13:43 UTC, justinmayer commented on api/client.go
> +// if the host is invalid.
Typo: `returns` → `returned`

2023-08-04 21:51 UTC, bmizerany commented
> I don't think this should be merged until accompanying documentation is added, preferably to the README

@justinmayer Where in the README should I add it to? I don't see any mention of environment variables in it ATM? Open to me picking a spot?

2023-08-05 02:59 UTC, drhino commented
in #271 i've added it below the rest api documention.
I also noticed that technoevangelist is writing an api.md in #289

Can't hurt to have it listed in both!

2023-08-05 12:06 UTC, justinmayer commented
I think underneath the REST API section in the README would be a good place to put this documentation.

And as @drhino suggested, perhaps also putting this information in the `api.md` documentation would be a good idea as well. 👍

2023-08-05 20:26 UTC, jmorganca commented
@bmizerany thanks for the PR! Great to see a friendly face 😊 .

Sorry for the delay in reviewing/merging. Need to consider the env var naming scheme we want here and will reply soon so we can get this merged!

2023-08-10 19:07 UTC, jmorganca commented on api/client.go
> +	envHost = os.Getenv("OLLAMA_CLIENT_HOST")
Possible to update this to `OLLAMA_HOST` (sorry for the switcheroo)

2023-08-10 19:08 UTC, jmorganca commented
Looks great! Just circled back with @pdevine and `OLLAMA_HOST` is best – similar to Docker and other tools. Thanks for the PR!!

2023-08-10 21:08 UTC, jmorganca commented on api/client.go
> +	envHost = os.Getenv("OLLAMA_CLIENT_HOST")
```suggestion
	envHost = os.Getenv("OLLAMA_HOST")
```

2023-08-14 01:45 UTC, jmorganca commented on api/client.go
> +// 1. The OLLAMA_CLIENT_HOST environment variable
```suggestion
// 1. The OLLAMA_HOST environment variable
```

2023-08-16 14:15 UTC, jmorganca approved these changes

2023-08-16 15:03 UTC, merged